### ISSUE TITLE
undefined: sort.Slice

### ISSUE THREAD

**Issue by grosser** [grosser/go-testcov#4]
```
(which go-testcov >/dev/null 2>&1 || go get github.com/grosser/go-testcov) && go-testcov
# github.com/grosser/go-testcov
../../../gopath/src/github.com/grosser/go-testcov/main.go:89: undefined: sort.Slice
make: *** [test] Error 2
```

**Comment by grosser** [comment]
looks like it's a go 1.7 issue ... so need to start testing on multiple go versions :/

@smo921

**Comment by grosser** [comment]
solution is to use a step with `language: go` so it uses go 1.8

```
matrix:
  include:
    - language: ruby
      script: bundle exec rake spec
    - language: go
      script: make test

```
